### ISSUE TITLE
General todo list from email

### ISSUE THREAD

**Issue by thgh** [weopendata/medea#60]
Dit lijstje werd gestuurd net na de laatste meeting

- [x] Record Searches - Workflow scherper afbakenen voor definiëren van zoekgebied (aanbevelingen richting web interface). Pieterjan doet aanzet tegen eind deze week.
- [x] Periode - Wordt én aan detectorist (indien gekend) én aan classificator gevraagd. Hoe hiermee omgaan op interface-niveau (bv. in vondsttitel, in vondstfiche, bij uitwisseling van gegevens tussen detectorist en classificator).
- [x] Pieterjan doet aanzet.
- [x] Piwik - We connect data werken dit verder uit en sturen voorbeeld van outputfile door tegen 22/08 ten laatste door. Lizzy geeft dan feedback om verder af te stemmen.
- [x] Doorzoekbare velden - Pieterjan levert de lijst aan met doorzoekbare velden.
- [x] Filtercategorieën - Momenteel kan gefilterd worden op categorie, periode, materiaal en techniek. Dit moet worden uitgebreid naar alle velden die gestructureerd kunnen worden ingegeven. Daarnaast is ook workflow status van de vondst een belangrijke filter.
- [x] Use cases - We connect data houdt naast de requirements op google drive ook rekening met de use cases aangegeven in de originele offerte. Voorbeelden zijn project tags voor registrators (use case IV.I.1), ingeven van referenties waarin vondsten worden aangehaald voor onderzoekers (IV.I.7.3)
- [x] Erkenning voor detectoristen - Suggesties: Meegeven hoeveel en hoe vaak vondstfiche geraadpleegd is als van erkenning voor detectoristen. We connect data stelt ook voor notifications te geven als vondstfiche ergens gelinkt wordt. Dit zou iets zijn voor derde iteratie
- [x] Opvolging - We Connect data communiceert de status van implementatie op google drive en geeft tijdig aan indien de geplande deadline (eind augustus) niet kan gehaald worden. Eerste helft van september wordt ook door We connect data tijd voorzien om voorafgaand aan de testen essentiële correcties te doen.
- [x] Brain-proposal - MEDEA geeft toegang tot voorstellen voor BRAIN call. Pieterjan stuurt nog mail over potentiële rol van We connect data.

**Comment by coreation** [comment]
* Back-end can now filter on all properties that have a drop down list value. They can be passed through the API endpoint as follows. 

- objectMaterial
- technique
- category
- period
- findSpot
- modificationTechniqueType
